# Generated by Django 2.1.3 on 2018-12-04 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='date published')),
                ('alt_text', models.TextField(verbose_name='alternate text')),
                ('comic_page_url', models.URLField(default='', max_length=500)),
                ('comic_url', models.URLField(max_length=500)),
                ('alt_comic_url', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ComicStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('rss_feed', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='comic_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.ComicStrip'),
        ),
    ]
