# Generated by Django 2.1.3 on 2018-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='comic_page_url',
            field=models.URLField(default='', max_length=500, unique=True),
        ),
    ]
