# Generated by Django 2.1.5 on 2019-01-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comicstrip_scraper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicstrip',
            name='scraper_name',
            field=models.CharField(choices=[('default', 'Default'), ('invisible_bread', 'Invisible Bread'), ('dilbert', 'Dilbert'), ('gocomics', 'Go Comics'), ('comics_kingdom', 'Comics Kingdom')], default='default', max_length=100),
        ),
    ]
